name: Pivotal Certified Professional Spring Developer Exam
name_cn: "Pivotal \u8BA4\u8BC1\u4E13\u4E1A Spring \u5F00\u53D1\u8005\u8003\u8BD5"
slug: pivotal-certified-professional-spring-developer-exam
