name: Logging in Java with the JDK 1.4 Logging API and Apache log4j
name_cn: "JDK 1.4 \u65E5\u5FD7 API \u4E0E Apache log4j \u7684 Java \u65E5\u5FD7\u8BB0\
  \u5F55"
slug: logging-in-java-with-the-jdk-14-logging-api-and-apache-log4j
