name: Beginning JavaTM EE 6 Platform with GlassFishTM 3
name_cn: "JavaTM EE 6 \u5E73\u53F0\u5165\u95E8\u6307\u5357\uFF08\u57FA\u4E8E GlassFishTM\
  \ 3\uFF09"
slug: beginning-javatm-ee-6-platform-with-glassfishtm-3
