name: Oracle Certified Professional Java SE 7 Programmer Exams 1Z0-804 and 1Z0-805
name_cn: "Oracle\u8BA4\u8BC1\u4E13\u5BB6Java SE 7\u7A0B\u5E8F\u5458\u8003\u8BD51Z0-804\u548C\
  1Z0-805"
slug: oracle-certified-professional-java-se-7-programmer-exams-1z0
