name: Pivotal Certified Spring Enterprise Integration Specialist Exam
name_cn: "Pivotal \u8BA4\u8BC1 Spring \u4F01\u4E1A\u96C6\u6210\u4E13\u5BB6\u8003\u8BD5"
slug: pivotal-certified-spring-enterprise-integration-specialist-e
